#![cfg_attr(not(debug_assertions),windows_subsystem="windows")]
use serde::{Deserialize,Serialize};
use std::{env,ffi::OsStr,io::{Read,Write},net::{TcpListener,TcpStream},os::windows::ffi::OsStrExt,ptr::{null,null_mut},thread};
use windows_sys::Win32::{Foundation::HANDLE,Graphics::Printing::*};
const ADDR:&str="127.0.0.1:17891";
#[derive(Serialize)] struct Printer{name:String,transport:&'static str}
#[derive(Deserialize)] struct Job{printer_name:String,data:Vec<u8>}
#[derive(Deserialize)] struct TcpJob{host:String,port:Option<u16>,data:Vec<u8>}
fn wide(s:&str)->Vec<u16>{OsStr::new(s).encode_wide().chain(Some(0)).collect()}
unsafe fn text(p:*mut u16)->String{if p.is_null(){return String::new()}let mut n=0;while unsafe{*p.add(n)}!=0{n+=1}String::from_utf16_lossy(unsafe{std::slice::from_raw_parts(p,n)})}
fn printers()->Result<Vec<Printer>,String>{let(mut need,mut count)=(0,0);let f=PRINTER_ENUM_LOCAL|PRINTER_ENUM_CONNECTIONS;unsafe{EnumPrintersW(f,null(),4,null_mut(),0,&mut need,&mut count)};if need==0{return Ok(vec![])}let mut b=vec![0u8;need as usize];if unsafe{EnumPrintersW(f,null(),4,b.as_mut_ptr(),need,&mut need,&mut count)}==0{return Err(std::io::Error::last_os_error().to_string())}let rows=unsafe{std::slice::from_raw_parts(b.as_ptr()as*const PRINTER_INFO_4W,count as usize)};Ok(rows.iter().filter_map(|r|{let name=unsafe{text(r.pPrinterName)};(!name.is_empty()).then_some(Printer{name,transport:"windows"})}).collect())}
fn print_raw(name:&str,data:&[u8])->Result<(),String>{if name.is_empty()||data.is_empty(){return Err("Printer and data are required".into())}let(n,d,r)=(wide(name),wide("Sawyun Receipt"),wide("RAW"));let mut h:HANDLE=null_mut();if unsafe{OpenPrinterW(n.as_ptr(),&mut h,null())}==0{return Err(format!("Cannot open printer: {}",std::io::Error::last_os_error()))}let info=DOC_INFO_1W{pDocName:d.as_ptr()as*mut _,pOutputFile:null_mut(),pDatatype:r.as_ptr()as*mut _};let result=(||{if unsafe{StartDocPrinterW(h,1,&info)}==0{return Err(std::io::Error::last_os_error().to_string())}if unsafe{StartPagePrinter(h)}==0{unsafe{EndDocPrinter(h)};return Err(std::io::Error::last_os_error().to_string())}let mut written=0;let ok=unsafe{WritePrinter(h,data.as_ptr()as*const _,data.len()as u32,&mut written)};unsafe{EndPagePrinter(h);EndDocPrinter(h)};if ok==0||written!=data.len()as u32{return Err(format!("Only {written} of {} bytes printed",data.len()))}Ok(())})();unsafe{ClosePrinter(h)};result}
fn print_tcp(host:&str,port:u16,data:&[u8])->Result<(),String>{if host.trim().is_empty()||data.is_empty(){return Err("Printer IP and data are required".into())}let addr=format!("{}:{}",host.trim(),port);let socket:std::net::SocketAddr=addr.parse().map_err(|_|"Invalid printer IP address")?;let mut stream=TcpStream::connect_timeout(&socket,std::time::Duration::from_secs(5)).map_err(|e|format!("Cannot connect to {addr}: {e}"))?;stream.set_write_timeout(Some(std::time::Duration::from_secs(10))).map_err(|e|e.to_string())?;stream.write_all(data).map_err(|e|format!("Wi-Fi print failed: {e}"))?;stream.flush().map_err(|e|e.to_string())}
fn allowed(o:&str)->bool{matches!(o,"http://localhost:5173"|"http://127.0.0.1:5173"|"https://pos.sawyuntech.com")||env::var("SAWYUN_PRINT_ORIGINS").unwrap_or_default().split(',').any(|v|v.trim()==o)}
fn header<'a>(h:&'a str,n:&str)->Option<&'a str>{h.lines().find_map(|l|{let(k,v)=l.split_once(':')?;k.eq_ignore_ascii_case(n).then(||v.trim())})}
fn reply(s:&mut TcpStream,status:&str,origin:Option<&str>,body:&str){let cors=origin.filter(|o|allowed(o)).map(|o|format!("Access-Control-Allow-Origin: {o}\r\nVary: Origin\r\n")).unwrap_or_default();let out=format!("HTTP/1.1 {status}\r\nContent-Type: application/json\r\n{cors}Access-Control-Allow-Methods: GET,POST,OPTIONS\r\nAccess-Control-Allow-Headers: Content-Type\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",body.len());let _=s.write_all(out.as_bytes());}
fn handle(mut s:TcpStream){let mut req=vec![];let mut buf=[0u8;8192];let end=loop{let n=match s.read(&mut buf){Ok(0)|Err(_)=>return,Ok(n)=>n};req.extend_from_slice(&buf[..n]);if req.len()>2_097_152{reply(&mut s,"413 Payload Too Large",None,r#"{"error":"Too large"}"#);return}if let Some(p)=req.windows(4).position(|w|w==b"\r\n\r\n"){break p+4}};let headers=match std::str::from_utf8(&req[..end]){Ok(v)=>v,Err(_)=>return};let mut first=headers.lines().next().unwrap_or("").split_whitespace();let(method,path)=(first.next().unwrap_or("").to_owned(),first.next().unwrap_or("").to_owned());let origin=header(headers,"Origin").map(str::to_owned);if origin.as_deref().is_some_and(|o|!allowed(o)){reply(&mut s,"403 Forbidden",None,r#"{"error":"Origin denied"}"#);return}if method=="OPTIONS"{reply(&mut s,"204 No Content",origin.as_deref(),"");return}let len=header(headers,"Content-Length").and_then(|v|v.parse().ok()).unwrap_or(0);while req.len()<end+len{let n=match s.read(&mut buf){Ok(0)|Err(_)=>break,Ok(n)=>n};req.extend_from_slice(&buf[..n])}let body=req.get(end..end+len).unwrap_or_default();match(method.as_str(),path.as_str()){("GET","/health")=>reply(&mut s,"200 OK",origin.as_deref(),r#"{"name":"Sawyun Print Agent","version":"0.1.0"}"#),("GET","/printers")=>match printers(){Ok(v)=>reply(&mut s,"200 OK",origin.as_deref(),&serde_json::to_string(&v).unwrap()),Err(e)=>reply(&mut s,"500 Internal Server Error",origin.as_deref(),&serde_json::json!({"error":e}).to_string())},("POST","/print")=>match serde_json::from_slice::<Job>(body){Ok(j)=>match print_raw(&j.printer_name,&j.data){Ok(())=>reply(&mut s,"200 OK",origin.as_deref(),r#"{"ok":true}"#),Err(e)=>reply(&mut s,"500 Internal Server Error",origin.as_deref(),&serde_json::json!({"error":e}).to_string())},Err(e)=>reply(&mut s,"400 Bad Request",origin.as_deref(),&serde_json::json!({"error":e.to_string()}).to_string())},("POST","/print-tcp")=>match serde_json::from_slice::<TcpJob>(body){Ok(j)=>match print_tcp(&j.host,j.port.unwrap_or(9100),&j.data){Ok(())=>reply(&mut s,"200 OK",origin.as_deref(),r#"{""ok"":true}"#),Err(e)=>reply(&mut s,"500 Internal Server Error",origin.as_deref(),&serde_json::json!({"error":e}).to_string())},Err(e)=>reply(&mut s,"400 Bad Request",origin.as_deref(),&serde_json::json!({"error":e.to_string()}).to_string())},_=>reply(&mut s,"404 Not Found",origin.as_deref(),r#"{"error":"Not found"}"#)}}
fn main()->std::io::Result<()>{let listener=TcpListener::bind(ADDR)?;for s in listener.incoming().flatten(){thread::spawn(||handle(s));}Ok(())}
