from __future__ import annotations


class EventType:
    # Product
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"

    VARIANT_CREATED = "VARIANT_CREATED"
    VARIANT_UPDATED = "VARIANT_UPDATED"
    VARIANT_DELETED = "VARIANT_DELETED"

    # Inventory
    STOCK_MOVEMENT_CREATED = "STOCK_MOVEMENT_CREATED"
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    OPENING_STOCK_SET = "OPENING_STOCK_SET"

    TRANSFER_CREATED = "TRANSFER_CREATED"
    TRANSFER_APPROVED = "TRANSFER_APPROVED"
    TRANSFER_EXECUTED = "TRANSFER_EXECUTED"
    TRANSFER_CANCELLED = "TRANSFER_CANCELLED"

    INVENTORY_RECONCILED = "INVENTORY_RECONCILED"
    INVENTORY_DISCREPANCY_DETECTED = "INVENTORY_DISCREPANCY_DETECTED"

    # Auth
    USER_LOGGED_IN = "USER_LOGGED_IN"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"

    # Tenant / User
    TENANT_CREATED = "TENANT_CREATED"
    USER_CREATED = "USER_CREATED"

    # Sales / Orders
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_COMPLETED = "ORDER_COMPLETED"
    ORDER_VOIDED = "ORDER_VOIDED"
    ORDER_CANCELLED = "ORDER_CANCELLED"

    # Payments
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"

    # Refunds
    REFUND_CREATED = "REFUND_CREATED"

    # Cashier Sessions
    CASHIER_SESSION_OPENED = "CASHIER_SESSION_OPENED"
    CASHIER_SESSION_CLOSED = "CASHIER_SESSION_CLOSED"

    # Devices
    DEVICE_REGISTERED = "DEVICE_REGISTERED"

    # Sync
    SYNC_STARTED = "SYNC_STARTED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    SYNC_FAILED = "SYNC_FAILED"
    OFFLINE_OPERATION_REPLAYED = "OFFLINE_OPERATION_REPLAYED"

    # Notifications
    LOW_STOCK = "LOW_STOCK"
    PURCHASE_ORDER_APPROVED = "PURCHASE_ORDER_APPROVED"
    GOODS_RECEIPT_CREATED = "GOODS_RECEIPT_CREATED"
    PAYABLE_OVERDUE = "PAYABLE_OVERDUE"
    CUSTOMER_BALANCE_HIGH = "CUSTOMER_BALANCE_HIGH"
    TRIAL_EXPIRING = "TRIAL_EXPIRING"
    SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING"
    SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"
    PAYMENT_PROOF_SUBMITTED = "PAYMENT_PROOF_SUBMITTED"
    PAYMENT_PROOF_APPROVED = "PAYMENT_PROOF_APPROVED"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"

    # Platform — Super-admin notifications
    BUSINESS_REGISTERED = "BUSINESS_REGISTERED"
    SUBSCRIPTION_ACTIVATED = "SUBSCRIPTION_ACTIVATED"
    SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED"
    SUBSCRIPTION_UPGRADED = "SUBSCRIPTION_UPGRADED"
    SUBSCRIPTION_DOWNGRADED = "SUBSCRIPTION_DOWNGRADED"

    # Referral / Commission / Wallet
    REFERRAL_CREATED = "REFERRAL_CREATED"
    COMMISSION_EARNED = "COMMISSION_EARNED"
    COMMISSION_REVERSED = "COMMISSION_REVERSED"
    PAYOUT_REQUESTED = "PAYOUT_REQUESTED"
    PAYOUT_APPROVED = "PAYOUT_APPROVED"
    PAYOUT_REJECTED = "PAYOUT_REJECTED"
    PAYOUT_COMPLETED = "PAYOUT_COMPLETED"
