from __future__ import annotations


class EventType:
    # Product
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"

    VARIANT_CREATED = "VARIANT_CREATED"
    VARIANT_UPDATED = "VARIANT_UPDATED"
    VARIANT_DELETED = "VARIANT_DELETED"

    # Inventory
    STOCK_MOVEMENT_CREATED = "STOCK_MOVEMENT_CREATED"
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    OPENING_STOCK_SET = "OPENING_STOCK_SET"

    TRANSFER_CREATED = "TRANSFER_CREATED"
    TRANSFER_APPROVED = "TRANSFER_APPROVED"
    TRANSFER_EXECUTED = "TRANSFER_EXECUTED"
    TRANSFER_CANCELLED = "TRANSFER_CANCELLED"

    INVENTORY_RECONCILED = "INVENTORY_RECONCILED"
    INVENTORY_DISCREPANCY_DETECTED = "INVENTORY_DISCREPANCY_DETECTED"

    # Auth
    USER_LOGGED_IN = "USER_LOGGED_IN"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"

    # Tenant / User
    TENANT_CREATED = "TENANT_CREATED"
    USER_CREATED = "USER_CREATED"

    # Sales / Orders (Phase 3)
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_COMPLETED = "ORDER_COMPLETED"
    ORDER_VOIDED = "ORDER_VOIDED"
    ORDER_CANCELLED = "ORDER_CANCELLED"

    # Payments (Phase 3)
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"

    # Refunds (Phase 3)
    REFUND_CREATED = "REFUND_CREATED"

    # Cashier Sessions (Phase 3)
    CASHIER_SESSION_OPENED = "CASHIER_SESSION_OPENED"
    CASHIER_SESSION_CLOSED = "CASHIER_SESSION_CLOSED"

    # Devices (Phase 4)
    DEVICE_REGISTERED = "DEVICE_REGISTERED"

    # Sync (Phase 4)
    SYNC_STARTED = "SYNC_STARTED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    SYNC_FAILED = "SYNC_FAILED"
    OFFLINE_OPERATION_REPLAYED = "OFFLINE_OPERATION_REPLAYED"
