from __future__ import annotations


class EventType:
    # Product
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"

    VARIANT_CREATED = "VARIANT_CREATED"
    VARIANT_UPDATED = "VARIANT_UPDATED"
    VARIANT_DELETED = "VARIANT_DELETED"

    # Inventory
    STOCK_MOVEMENT_CREATED = "STOCK_MOVEMENT_CREATED"
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    OPENING_STOCK_SET = "OPENING_STOCK_SET"

    TRANSFER_CREATED = "TRANSFER_CREATED"
    TRANSFER_APPROVED = "TRANSFER_APPROVED"
    TRANSFER_EXECUTED = "TRANSFER_EXECUTED"
    TRANSFER_CANCELLED = "TRANSFER_CANCELLED"

    INVENTORY_RECONCILED = "INVENTORY_RECONCILED"
    INVENTORY_DISCREPANCY_DETECTED = "INVENTORY_DISCREPANCY_DETECTED"

    # Auth
    USER_LOGGED_IN = "USER_LOGGED_IN"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"

    # Tenant / User
    TENANT_CREATED = "TENANT_CREATED"
    USER_CREATED = "USER_CREATED"
